spring:
  # JPA Setting
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  # H2 Setting
  h2:
    console:
      enabled: true
      path: /h2-console
  # Database Setting
  datasource:
    drvier-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
logging:
  level:
    # JPA Setting
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
