spring:
  # H2 Setting
  h2:
    console:
      enabled: true
      path: /h2-console
  # Database Setting
  datasource:
    drvier-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: